apiVersion: v1
kind: Service
metadata:
  name: ragengine-gpu-public
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    kaito.sh/ragengine: ragengine-gpu
  type: LoadBalancer